<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA9xwBgL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA9xwBgL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA9xwBgL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA9xwBgL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA9xwBgL\App_KernelDevDebugContainer([
    'container.build_hash' => 'A9xwBgL',
    'container.build_id' => '543bae28',
    'container.build_time' => 1619790057,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA9xwBgL');
